apiVersion: v1
kind: ConfigMap
metadata:
    name: fluentd-config
    namespace: default
    labels:
      addonmanager.kubernetes.io/mode: Reconcile
data:
    containers.input.conf: |-
       <source>
         @id fluentd-containers.log
         @type tail
         path /var/log/containers/*.log
         pos_file /var/log/es-containers.log.pos
         time_format %Y-%m-%dT%H:%M:$S.%NZ
         localtime
         tag raw.kubernetes.*
         format json
         read_from_head true
       </source>
       
       # Correct Setting
       # https://github.com/GoogleCloudPlatform/fluent-plugin-detect-exception
       <match raw.kubernetes.**>
         @id raw.kubernetes
         @type detect_exceptions
         remove_tag_prefix raw
         message log
         stream stream
         multiline_flush_interval 5
         max_bytes 500000
         max_lines 1000
       </match>
  
    output.conf: |-
       <filter kubernetes.**>
          @type kubernetes_metadata
       </filter>
       <match **>
         @id elasticsearch
         @type elasticsearch
         @log_level info
         include_tag_key true
         host elasticsearch
         port 9200
         logstash_format true
         logstash_prefix k8s  # Add Prefix
         request_timeout  30s
         <buffer>
           @type file
           path /var/log/fluentd-buffers/kubernetes.system.buffer
           flush_mode interval
           retry_type exponential_backoff
           flush_thread_count 2
           flush_interval 5s
           retry_forever
           retry_max_interval 30
           chunk_limit_size 2M
           queue_limit_length 8
           overflow_action block
         </buffer>
       </match>
