apiVersion: v1
kind: ConfigMap
metadata:
    name: fluentd-config
    namespace: default
    labels:
      addonmanager.kubernetes.io/mode: Reconcile
data:
    system.conf: |-
       <system>
         root_dir /tmp/fluentd-buffers/
       </system>
    containers.input.conf: |-
       <source>
         @id fluentd-containers.log
         @type tail
         path /var/log/containers/ricxapp-*
         pos_file /var/log/es-containers.log.pos
         tag raw.kubernetes.*
         read_from_head true
         <parse>
            @type multi_format
            <pattern>
              format json
              time_key time
              time_format %Y-%m-%dT%H:%M:%S.%NZ
            </pattern>
            <pattern>
              format /^(?<time>.+) (?<stream>stdout|stderr) [^ ]* (?<log>.*)$/
              time_format %Y-%m-%dT%H:%M:%S.%N%:z  # It is wired here
            </pattern>
         </parse>
       </source>
       
       # Correct Setting
       # https://github.com/GoogleCloudPlatform/fluent-plugin-detect-exception
       <match raw.kubernetes.**>
         @id raw.kubernetes
         @type detect_exceptions
         remove_tag_prefix raw
         message log
         stream stream
         multiline_flush_interval 5
         max_bytes 500000
         max_lines 1000
       </match>

       <filter **>
         @id filter_concat
         @type concat
         key message
         multiline_end_regexp /\n$/
         seperator ""
       </filter>

       <filter kubernetes.**>
         @id filter_kubernetes_metadata
         @type kubernetes_metadata
       </filter>

       <filter kubernetes.**>
         @id filter_parser
         @type parser
         key_name log
         reserve_data true
         remove_key_name_filed true
         <parse>
           @type multi_format
           <pattern>
             format json
           </pattern>
           <pattern>
             format none
           </pattern>
         </parse>
       </filter>


       <filter kubernetes.**>
         @type record_transformer
         remove_keys $.docker.container_id,$.kubernetes.container_image_id,$.kubernetes.namespace_id,$.kubernetes.master_url,$.kubernetes.labels.pod-template-hash
       </filter>

       <filter kubernetes.**>
         @id filter_log
         @type grep
         <regexp>
           key $.kubernetes.labels.logging
           pattern ^true$
         </regexp>
       </filter>

    forward.input.conf: |-
       <source>
         @id forward
         @type forward
       </source>

    output.conf: |-
       <match **>
         @id elasticsearch
         @type elasticsearch
         @log_level info
         include_tag_key true
         host localhost
         port 9200
         logstash_format true
         logstash_prefix k8s
         request_timeout  30s
         <buffer>
           @type file
           path /var/log/fluentd-buffers/kubernetes.system.buffer
           flush_mode interval
           retry_type exponential_backoff
           flush_thread_count 2
           flush_interval 5s
           retry_forever
           retry_max_interval 30
           chunk_limit_size 2M
           queue_limit_length 8
           overflow_action block
         </buffer>
       </match>
